export const sampleProducts = [
  {
    name: "Áo thun cotton unisex",
    slug: "ao-thun-cotton-unisex",
    description:
      "Áo thun cotton 100%, form rộng unisex, thấm hút mồ hôi tốt. Nhiều màu, nhiều size từ S đến XL.",
    price: 149000,
    compareAt: 199000,
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600",
    stock: 0,
    category: "Thời trang",
    optionName1: "Màu sắc",
    optionValues1: "Trắng, Đen, Xanh navy",
    optionName2: "Size",
    optionValues2: "S, M, L, XL",
  },
  {
    name: "Giày sneaker trắng basic",
    slug: "giay-sneaker-trang-basic",
    description:
      "Giày sneaker trắng phối màu tối giản, đế cao su êm ái, dễ phối đồ đi học đi làm.",
    price: 359000,
    compareAt: 459000,
    imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600",
    stock: 0,
    category: "Giày dép",
    optionName1: "Size",
    optionValues1: "38, 39, 40, 41, 42",
    optionName2: null,
    optionValues2: "",
  },
  {
    name: "Balo laptop chống nước",
    slug: "balo-laptop-chong-nuoc",
    description:
      "Balo chất liệu chống nước, ngăn đựng laptop 15.6 inch riêng biệt, nhiều ngăn tiện lợi.",
    price: 259000,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600",
    stock: 40,
    category: "Phụ kiện",
  },
  {
    name: "Tai nghe bluetooth không dây",
    slug: "tai-nghe-bluetooth-khong-day",
    description:
      "Tai nghe true wireless, chống ồn, pin 6 giờ liên tục, kèm hộp sạc 24 giờ dự phòng.",
    price: 299000,
    compareAt: 399000,
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600",
    stock: 25,
    category: "Điện tử",
  },
  {
    name: "Bát sứ họa tiết",
    slug: "bat-su-hoa-tiet",
    description: "Bát sứ men trắng họa tiết cổ điển, an toàn với lò vi sóng, nhiều cỡ.",
    price: 39000,
    imageUrl: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600",
    stock: 0,
    category: "Gia dụng",
    optionName1: "Cỡ",
    optionValues1: "Nhỏ (10cm), Vừa (14cm), Lớn (18cm)",
    optionName2: null,
    optionValues2: "",
  },
  {
    name: "Đồng hồ thể thao dây silicon",
    slug: "dong-ho-the-thao-day-silicon",
    description:
      "Đồng hồ thể thao chống nước, mặt kính cường lực, dây silicon mềm mại thoải mái.",
    price: 219000,
    compareAt: 279000,
    imageUrl: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600",
    stock: 35,
    category: "Phụ kiện",
  },
];
