export const sampleProducts = [
  {
    name: "Giỏ mây đan tay đa năng",
    slug: "gio-may-dan-tay-da-nang",
    description:
      "Giỏ đan thủ công từ mây tự nhiên, dùng đựng đồ dùng, trái cây, hoặc trang trí góc nhà. Form tròn chắc chắn, viền được gia cố kỹ.",
    price: 189000,
    compareAt: 249000,
    imageUrl: "https://images.unsplash.com/photo-1632574231053-2dda4c5774eb?w=600",
    stock: 0,
    category: "Giỏ & Rổ",
    optionName1: "Cỡ",
    optionValues1: "Nhỏ (20cm), Vừa (30cm), Lớn (40cm)",
    optionName2: null,
    optionValues2: "",
  },
  {
    name: "Chậu bọc mây trồng cây",
    slug: "chau-boc-may-trong-cay",
    description:
      "Vỏ bọc chậu cây bằng mây đan, tôn dáng chậu cảnh, phù hợp trang trí phòng khách, ban công theo phong cách mộc mạc.",
    price: 159000,
    imageUrl: "https://images.unsplash.com/photo-1588706838478-acc49b5d9fcf?w=600",
    stock: 0,
    category: "Trang trí",
    optionName1: "Cỡ",
    optionValues1: "Nhỏ, Vừa, Lớn",
    optionName2: null,
    optionValues2: "",
  },
  {
    name: "Ghế mây thư giãn",
    slug: "ghe-may-thu-gian",
    description:
      "Ghế khung mây đan thủ công, kèm đệm ngồi êm ái. Phù hợp đặt góc ban công, sân vườn hoặc phòng khách phong cách tự nhiên.",
    price: 890000,
    compareAt: 1090000,
    imageUrl: "https://images.unsplash.com/photo-1634212926265-f84991da274d?w=600",
    stock: 15,
    category: "Nội thất",
  },
  {
    name: "Khay mây tre đựng trái cây",
    slug: "khay-may-tre-dung-trai-cay",
    description:
      "Khay đan mây tre dùng đựng trái cây, bánh kẹo khi tiếp khách, hoặc trang trí bàn ăn. Nhiều cỡ để chọn theo nhu cầu sử dụng.",
    price: 99000,
    imageUrl: "https://images.unsplash.com/photo-1632574231053-2dda4c5774eb?w=600",
    stock: 0,
    category: "Giỏ & Rổ",
    optionName1: "Cỡ",
    optionValues1: "20cm, 25cm, 30cm",
    optionName2: null,
    optionValues2: "",
  },
];
